<?php

namespace Database\Seeders;

use App\Models\Quality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QualitySeeder extends Seeder {
    public function run() {
        Quality::create([
            'monitoring_point_id' => 1,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 1,
            'wpi' => 1,
            'temperature' => 18.9,
            'ph' => 7.72,
            'dhl' => null,
            'tds' => 46.8,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 1,
            'nh_2' => 0,
            'clorin' => 7.24,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 2,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 1,
            'wpi' => 2,
            'temperature' => 20.9,
            'ph' => 8.45,
            'dhl' => null,
            'tds' => 56.7,
            'tss' => 46, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 13.1,
            'no_2' => 0.1,
            'no_3' => 2.5,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.12,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 2400,
            'total_coliform' => 4600,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 3,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 2,
            'wpi' => 3,
            'temperature' => 21.1,
            'ph' => 6.58,
            'dhl' => null,
            'tds' => 136.1,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 6.2,
            'nh_2' => 0,
            'clorin' => 9.9,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 4,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 2,
            'wpi' => 4,
            'temperature' => 22.2,
            'ph' => 8.17,
            'dhl' => null,
            'tds' => 93.7,
            'tss' => 114, 
            'do' => 5.2,
            'bod' => 12,
            'cod' => 39.4,
            'no_2' => 0.03,
            'no_3' => 4.1,
            'nh_2' => 0.0038,
            'clorin' => 7.24,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 5,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 3,
            'wpi' => 5,
            'temperature' => 22.4,
            'ph' => 8.28,
            'dhl' => null,
            'tds' => 94.9,
            'tss' => 142, 
            'do' => 5.6,
            'bod' => 6,
            'cod' => 19.7,
            'no_2' => 0.03,
            'no_3' => 4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 6,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 3,
            'wpi' => 6,
            'temperature' => 24,
            'ph' => 24,
            'dhl' => null,
            'tds' => 136.9,
            'tss' => 18, 
            'do' => 6.3,
            'bod' => 8,
            'cod' => 23,
            'no_2' => 0.04,
            'no_3' => 3.3,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 7,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 4,
            'wpi' => 7,
            'temperature' => 24.8,
            'ph' => 8.67,
            'dhl' => null,
            'tds' => 147.2,
            'tss' => 40, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.04,
            'no_3' => 2.8,
            'nh_2' => 0.014,
            'clorin' => 14.8,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 8,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 4,
            'wpi' => 8,
            'temperature' => 23.3,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 138.3,
            'tss' => 68, 
            'do' => 5.7,
            'bod' => 5,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 9,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 5,
            'wpi' => 9,
            'temperature' => 22.8,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 130.4,
            'tss' => 94, 
            'do' => 6.2,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 14.8,
            'total_fosfat' => 0.19,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 10,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 4,
            'wpi' => 10,
            'temperature' => 22.5,
            'ph' => 8.79,
            'dhl' => null,
            'tds' => 132.2,
            'tss' => 42, 
            'do' => 5.7,
            'bod' => 7,
            'cod' => 19.7,
            'no_2' => 0.04,
            'no_3' => 2.7,
            'nh_2' => 0.031,
            'clorin' => 14.8,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 11,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 3,
            'wpi' => 11,
            'temperature' => 23.2,
            'ph' => 8.49,
            'dhl' => null,
            'tds' => 115,
            'tss' => 50, 
            'do' => 6.2,
            'bod' => 5,
            'cod' => 13.1,
            'no_2' => 0.03,
            'no_3' => 3.5,
            'nh_2' => 0.0018,
            'clorin' => 7,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 12,
            'users_id' => 0,
            'sampling_time_id' => 1,
            'wqi' => 2,
            'wpi' => 12,
            'temperature' => 20.6,
            'ph' => 8.46,
            'dhl' => null,
            'tds' => 71.3,
            'tss' => 70, 
            'do' => 6.7,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.02,
            'no_3' => 3.8,
            'nh_2' => 0.0002,
            'clorin' => 7.24,
            'total_fosfat' => 0.014,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 1,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 1,
            'wpi' => 12,
            'temperature' => 18.9,
            'ph' => 7.72,
            'dhl' => null,
            'tds' => 46.8,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 1,
            'nh_2' => 0,
            'clorin' => 7.24,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 2,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 7,
            'wpi' => 11,
            'temperature' => 20.9,
            'ph' => 8.45,
            'dhl' => null,
            'tds' => 56.7,
            'tss' => 46, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 13.1,
            'no_2' => 0.1,
            'no_3' => 2.5,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.12,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 2400,
            'total_coliform' => 4600,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 3,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 8,
            'wpi' => 10,
            'temperature' => 21.1,
            'ph' => 6.58,
            'dhl' => null,
            'tds' => 136.1,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 6.2,
            'nh_2' => 0,
            'clorin' => 9.9,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 4,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 5,
            'wpi' => 9,
            'temperature' => 22.2,
            'ph' => 8.17,
            'dhl' => null,
            'tds' => 93.7,
            'tss' => 114, 
            'do' => 5.2,
            'bod' => 12,
            'cod' => 39.4,
            'no_2' => 0.03,
            'no_3' => 4.1,
            'nh_2' => 0.0038,
            'clorin' => 7.24,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 5,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 8,
            'wpi' => 8,
            'temperature' => 22.4,
            'ph' => 8.28,
            'dhl' => null,
            'tds' => 94.9,
            'tss' => 142, 
            'do' => 5.6,
            'bod' => 6,
            'cod' => 19.7,
            'no_2' => 0.03,
            'no_3' => 4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 6,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 2,
            'wpi' => 7,
            'temperature' => 24,
            'ph' => 24,
            'dhl' => null,
            'tds' => 136.9,
            'tss' => 18, 
            'do' => 6.3,
            'bod' => 8,
            'cod' => 23,
            'no_2' => 0.04,
            'no_3' => 3.3,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 7,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 1,
            'wpi' => 6,
            'temperature' => 24.8,
            'ph' => 8.67,
            'dhl' => null,
            'tds' => 147.2,
            'tss' => 40, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.04,
            'no_3' => 2.8,
            'nh_2' => 0.014,
            'clorin' => 14.8,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 8,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 9,
            'wpi' => 5,
            'temperature' => 23.3,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 138.3,
            'tss' => 68, 
            'do' => 5.7,
            'bod' => 5,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 9,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 11,
            'wpi' => 4,
            'temperature' => 22.8,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 130.4,
            'tss' => 94, 
            'do' => 6.2,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 14.8,
            'total_fosfat' => 0.19,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 10,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 23,
            'wpi' => 3,
            'temperature' => 22.5,
            'ph' => 8.79,
            'dhl' => null,
            'tds' => 132.2,
            'tss' => 42, 
            'do' => 5.7,
            'bod' => 7,
            'cod' => 19.7,
            'no_2' => 0.04,
            'no_3' => 2.7,
            'nh_2' => 0.031,
            'clorin' => 14.8,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 11,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 11,
            'wpi' => 2,
            'temperature' => 23.2,
            'ph' => 8.49,
            'dhl' => null,
            'tds' => 115,
            'tss' => 50, 
            'do' => 6.2,
            'bod' => 5,
            'cod' => 13.1,
            'no_2' => 0.03,
            'no_3' => 3.5,
            'nh_2' => 0.0018,
            'clorin' => 7,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 12,
            'users_id' => 0,
            'sampling_time_id' => 2,
            'wqi' => 10,
            'wpi' => 1,
            'temperature' => 20.6,
            'ph' => 8.46,
            'dhl' => null,
            'tds' => 71.3,
            'tss' => 70, 
            'do' => 6.7,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.02,
            'no_3' => 3.8,
            'nh_2' => 0.0002,
            'clorin' => 7.24,
            'total_fosfat' => 0.014,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 1,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 1,
            'wpi' => 1,
            'temperature' => 18.9,
            'ph' => 7.72,
            'dhl' => null,
            'tds' => 46.8,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 1,
            'nh_2' => 0,
            'clorin' => 7.24,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 2,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 1,
            'wpi' => 2,
            'temperature' => 20.9,
            'ph' => 8.45,
            'dhl' => null,
            'tds' => 56.7,
            'tss' => 46, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 13.1,
            'no_2' => 0.1,
            'no_3' => 2.5,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.12,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 2400,
            'total_coliform' => 4600,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 3,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 2,
            'wpi' => 3,
            'temperature' => 21.1,
            'ph' => 6.58,
            'dhl' => null,
            'tds' => 136.1,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 6.2,
            'nh_2' => 0,
            'clorin' => 9.9,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 4,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 2,
            'wpi' => 4,
            'temperature' => 22.2,
            'ph' => 8.17,
            'dhl' => null,
            'tds' => 93.7,
            'tss' => 114, 
            'do' => 5.2,
            'bod' => 12,
            'cod' => 39.4,
            'no_2' => 0.03,
            'no_3' => 4.1,
            'nh_2' => 0.0038,
            'clorin' => 7.24,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 5,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 3,
            'wpi' => 5,
            'temperature' => 22.4,
            'ph' => 8.28,
            'dhl' => null,
            'tds' => 94.9,
            'tss' => 142, 
            'do' => 5.6,
            'bod' => 6,
            'cod' => 19.7,
            'no_2' => 0.03,
            'no_3' => 4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 6,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 3,
            'wpi' => 6,
            'temperature' => 24,
            'ph' => 24,
            'dhl' => null,
            'tds' => 136.9,
            'tss' => 18, 
            'do' => 6.3,
            'bod' => 8,
            'cod' => 23,
            'no_2' => 0.04,
            'no_3' => 3.3,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 7,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 4,
            'wpi' => 7,
            'temperature' => 24.8,
            'ph' => 8.67,
            'dhl' => null,
            'tds' => 147.2,
            'tss' => 40, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.04,
            'no_3' => 2.8,
            'nh_2' => 0.014,
            'clorin' => 14.8,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 8,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 4,
            'wpi' => 8,
            'temperature' => 23.3,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 138.3,
            'tss' => 68, 
            'do' => 5.7,
            'bod' => 5,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 9,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 5,
            'wpi' => 9,
            'temperature' => 22.8,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 130.4,
            'tss' => 94, 
            'do' => 6.2,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 14.8,
            'total_fosfat' => 0.19,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 10,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 4,
            'wpi' => 10,
            'temperature' => 22.5,
            'ph' => 8.79,
            'dhl' => null,
            'tds' => 132.2,
            'tss' => 42, 
            'do' => 5.7,
            'bod' => 7,
            'cod' => 19.7,
            'no_2' => 0.04,
            'no_3' => 2.7,
            'nh_2' => 0.031,
            'clorin' => 14.8,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 11,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 3,
            'wpi' => 11,
            'temperature' => 23.2,
            'ph' => 8.49,
            'dhl' => null,
            'tds' => 115,
            'tss' => 50, 
            'do' => 6.2,
            'bod' => 5,
            'cod' => 13.1,
            'no_2' => 0.03,
            'no_3' => 3.5,
            'nh_2' => 0.0018,
            'clorin' => 7,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 12,
            'users_id' => 0,
            'sampling_time_id' => 3,
            'wqi' => 2,
            'wpi' => 12,
            'temperature' => 20.6,
            'ph' => 8.46,
            'dhl' => null,
            'tds' => 71.3,
            'tss' => 70, 
            'do' => 6.7,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.02,
            'no_3' => 3.8,
            'nh_2' => 0.0002,
            'clorin' => 7.24,
            'total_fosfat' => 0.014,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 1,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 1,
            'wpi' => 12,
            'temperature' => 18.9,
            'ph' => 7.72,
            'dhl' => null,
            'tds' => 46.8,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 1,
            'nh_2' => 0,
            'clorin' => 7.24,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 2,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 7,
            'wpi' => 11,
            'temperature' => 20.9,
            'ph' => 8.45,
            'dhl' => null,
            'tds' => 56.7,
            'tss' => 46, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 13.1,
            'no_2' => 0.1,
            'no_3' => 2.5,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.12,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 2400,
            'total_coliform' => 4600,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 3,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 8,
            'wpi' => 10,
            'temperature' => 21.1,
            'ph' => 6.58,
            'dhl' => null,
            'tds' => 136.1,
            'tss' => 0, 
            'do' => 0,
            'bod' => 0,
            'cod' => 0,
            'no_2' => 0.01,
            'no_3' => 6.2,
            'nh_2' => 0,
            'clorin' => 9.9,
            'total_fosfat' => 0,
            'fenol' => 0,
            'oil' => 0,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0
        ]);

        Quality::create([
            'monitoring_point_id' => 4,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 5,
            'wpi' => 9,
            'temperature' => 22.2,
            'ph' => 8.17,
            'dhl' => null,
            'tds' => 93.7,
            'tss' => 114, 
            'do' => 5.2,
            'bod' => 12,
            'cod' => 39.4,
            'no_2' => 0.03,
            'no_3' => 4.1,
            'nh_2' => 0.0038,
            'clorin' => 7.24,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 0,
            'total_coliform' => 0,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 5,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 8,
            'wpi' => 8,
            'temperature' => 22.4,
            'ph' => 8.28,
            'dhl' => null,
            'tds' => 94.9,
            'tss' => 142, 
            'do' => 5.6,
            'bod' => 6,
            'cod' => 19.7,
            'no_2' => 0.03,
            'no_3' => 4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 6,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 2,
            'wpi' => 7,
            'temperature' => 24,
            'ph' => 24,
            'dhl' => null,
            'tds' => 136.9,
            'tss' => 18, 
            'do' => 6.3,
            'bod' => 8,
            'cod' => 23,
            'no_2' => 0.04,
            'no_3' => 3.3,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.17,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 7,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 1,
            'wpi' => 6,
            'temperature' => 24.8,
            'ph' => 8.67,
            'dhl' => null,
            'tds' => 147.2,
            'tss' => 40, 
            'do' => 6.4,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.04,
            'no_3' => 2.8,
            'nh_2' => 0.014,
            'clorin' => 14.8,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 8,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 9,
            'wpi' => 5,
            'temperature' => 23.3,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 138.3,
            'tss' => 68, 
            'do' => 5.7,
            'bod' => 5,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 9.9,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 9,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 11,
            'wpi' => 4,
            'temperature' => 22.8,
            'ph' => 8.53,
            'dhl' => null,
            'tds' => 130.4,
            'tss' => 94, 
            'do' => 6.2,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.03,
            'no_3' => 3.4,
            'nh_2' => 0.0002,
            'clorin' => 14.8,
            'total_fosfat' => 0.19,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 10,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 23,
            'wpi' => 3,
            'temperature' => 22.5,
            'ph' => 8.79,
            'dhl' => null,
            'tds' => 132.2,
            'tss' => 42, 
            'do' => 5.7,
            'bod' => 7,
            'cod' => 19.7,
            'no_2' => 0.04,
            'no_3' => 2.7,
            'nh_2' => 0.031,
            'clorin' => 14.8,
            'total_fosfat' => 0.21,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 11,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 11,
            'wpi' => 2,
            'temperature' => 23.2,
            'ph' => 8.49,
            'dhl' => null,
            'tds' => 115,
            'tss' => 50, 
            'do' => 6.2,
            'bod' => 5,
            'cod' => 13.1,
            'no_2' => 0.03,
            'no_3' => 3.5,
            'nh_2' => 0.0018,
            'clorin' => 7,
            'total_fosfat' => 0.16,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);

        Quality::create([
            'monitoring_point_id' => 12,
            'users_id' => 0,
            'sampling_time_id' => 4,
            'wqi' => 10,
            'wpi' => 1,
            'temperature' => 20.6,
            'ph' => 8.46,
            'dhl' => null,
            'tds' => 71.3,
            'tss' => 70, 
            'do' => 6.7,
            'bod' => 4,
            'cod' => 9.86,
            'no_2' => 0.02,
            'no_3' => 3.8,
            'nh_2' => 0.0002,
            'clorin' => 7.24,
            'total_fosfat' => 0.014,
            'fenol' => 0.1,
            'oil' => 0.1,
            'detergent' => 0,
            'fecal_coliform' => 4600,
            'total_coliform' => 11000,
            'cyanide' => 0.005,
            'h2s' => 0.04
        ]);
        
    }
}
